### ISSUE TITLE
Официальная поддержка модулей Почты России

### ISSUE THREAD

**Issue by JointStockCompany** [qnub/ru-post-soap-client#14]
Добрый день!

Мы невероятно нуждаемся в создании SDK и разработке официальных модулей для платформы otpravka точка pochta точка ru ради встраивания во все основные CMS / CRM / ERP. На текущий момент у нас нет возможности организации какого-то партнёрства и единственный доступный вариант это трудоустройство в Почту России. Подробные описания вакансий доступны на hr точка pochta точка tech слэш teams слэш maksim-zhukov

Пишите на maxim точка zhukov собака russianpost точка ru, очень надеюсь на обратную связь. 

Хорошего дня!

**Comment by qnub** [comment]
Ого, так меня ещё не хантили :) Спасибо, но у меня совершенно неотложный проект на ближайшую перспективу…
